#!/bin/bash
set -e

# Use virtual environment if available
if [ -f ".venv/bin/python" ]; then
    PYTHON=".venv/bin/python"
else
    PYTHON="python"
fi

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}=== Novita SDK Model Generation ===${NC}\n"

# Configuration
OPENAPI_SPEC="openapi/novita-api.yaml"
OUTPUT_FILE="src/novita/generated/models.py"
OUTPUT_DIR="src/novita/generated"
PYTHON_VERSION="3.11"



# Check if OpenAPI spec exists
if [ ! -f "$OPENAPI_SPEC" ]; then
    echo -e "${YELLOW}Warning: OpenAPI spec not found at $OPENAPI_SPEC${NC}"
    exit 1
fi

echo -e "${BLUE}Step 1: Generating Pydantic models from OpenAPI spec...${NC}"
$PYTHON -m datamodel_code_generator \
    --input "$OPENAPI_SPEC" \
    --output "$OUTPUT_FILE" \
    --target-python-version "$PYTHON_VERSION" \
    --output-model-type pydantic_v2.BaseModel \
    --use-annotated \
    --use-standard-collections \
    --use-schema-description \
    --field-constraints \
    --use-double-quotes \
    --snake-case-field \
    --enum-field-as-literal one \
    --collapse-root-models \
    --use-title-as-name

echo -e "${GREEN}✓ Models generated successfully${NC}\n"

echo -e "${BLUE}Step 2: Adding __init__.py to generated package...${NC}"
cat > src/novita/generated/__init__.py << 'EOF'
"""Auto-generated models from OpenAPI specification.

DO NOT EDIT THIS FILE MANUALLY.
This file is automatically generated from the OpenAPI spec.
Run `./scripts/generate_models.sh` to regenerate.
"""

from .models import *
EOF

echo -e "${GREEN}✓ __init__.py created${NC}\n"

echo -e "${BLUE}Step 3: Formatting generated code with ruff...${NC}"
ruff format "$OUTPUT_FILE" src/novita/generated/__init__.py 2>/dev/null || echo "Ruff format skipped"
ruff check --fix "$OUTPUT_FILE" src/novita/generated/__init__.py 2>/dev/null || echo "Ruff check skipped"

echo -e "${GREEN}✓ Code formatted${NC}\n"

echo -e "${GREEN}=== Generation Complete! ===${NC}"
echo -e "Generated models: ${BLUE}$OUTPUT_FILE${NC}"
echo -e "\nNext steps:"
echo -e "  1. Review the generated models in src/novita/generated/models.py"
echo -e "  2. Update your resource classes to import from novita.generated.models"
echo -e "  3. Run tests to verify everything works"
